### ISSUE TITLE
ServerDataSource does not support multiple sort fields

### ISSUE THREAD

**Issue by glam2000** [dj-fiorex/angular2-smart-table#113]
In the demos, the ServerDataSource includes a table with all the fields sortable.  When one is selected the appropriate message, however when multiple columns have sorting, only the first selection is used in the call to the backend.

local url: `/examples/populate-from-server`
backend call parameters: `_sort=id&_order=ASC&_page=1&_limit=10`

**Comment by uap-universe** [comment]
Yes, the fix in 2.5.0 that made sorting for multiple columns work, seemingly missed that one.
