### ISSUE TITLE
Angular 15 Support

### ISSUE THREAD

**Issue by uap-universe** [dj-fiorex/angular2-smart-table#114]
Add support for Angular 15.

**Comment by abrahampe** [comment]
I will be right here waiting for you

**Comment by NickBoomBoom** [comment]
mark

**Comment by uap-universe** [comment]
I want to release 2.8.0 this week. If you want to have it right now, please clone the repository and run the build script. You will see a `dist` directory generated and there will be a `angular2-smart-table` directory within. You can specifiy the full path in your package.json for testing. Like so:

```
"angular2-smart-table": "C:\\Development\\GitHub\\angular2-smart-table\\dist\\angular2-smart-table",
```

After the release you can of course change that to

```
"angular2-smart-table": "~2.8.0",
```

**Comment by uap-universe** [comment]
@abrahampe the release 2.8.0 is now available in the NPM registry

**Comment by abrahampe** [comment]
Thanks! I will update the package.json here! Have a good day!
