### ISSUE TITLE
Angular 16 Support

### ISSUE THREAD

**Issue by uap-universe** [dj-fiorex/angular2-smart-table#125]
## Updated 2023-05-24

In May 2023 Angular 16 has been released.

This release removes the ngcc (Angular Compatibility Compiler) making some dependencies incompatible.

So far we have identified ng2-completer and angular2-multiselect-dropdown to be unusable anymore.

We can add Angular 16 support in the following way:

* we will add the version to the list of supported versions
* this will constitute a new *major* release 3.0.0
* we remove Angular 13 from the list of supported versions (LTS has expired)
* we will consider some minor breaking changes (i.e. those which require only few adaptions in your projects) among the open issues and check if we can take the opportunity to resolve them
* we **remove** the features that require the unmaintained dependencies
* for more severe breaking changes we will introduce another major release 4.0.0

In order to understand the effect such a change would have, I have opened a poll #132 

The idea is to release a 3.0.0 that is mostly compatible to your projects and then - some day in the future - a 4.0.0 which is allowed to break more stuff.

**Comment by uap-universe** [comment]
Unfortunately, Angular 16 support will **NOT** be available in 2.9.0, because various libraries the smart table depends on are not Ivy compatible and ngcc has been removed in Angular 16.

**Comment by pj-alvarado10** [comment]
The principal problem in angular 16 is the ModuleWithProviders in the module ng2-completer. Some actions could be deleted in angular 16, but I am really sad because smart table doesn't work in angular 16 :(

**Comment by pj-alvarado10** [comment]
Yes, you have reason. But I think that maybe angular2-multiselect-dropdown and other features maybe could be removed only to angular 16, but I don't know if ng2-completer could be removed or replaced.

**Comment by uap-universe** [comment]
Works for me - no commits since 2020 (ng2-completer) and 2021 (angular2-multiselect-dropdown), but that changes the plan for the smart-table quite a bit. So the next major release 3.0.0 would already introduce a considerable amount of breaking changes.

Let's have a poll how bad this would be #132

**Comment by uap-universe** [comment]
The poll is now running for a while and we have four votes. While I am perfectly aware that the poll might not reach so many people, I am willing to take the risk and start planning the version 3.0.0.

**Comment by pj-alvarado10** [comment]
It's great! But when I install the library with npm, the changes without ng2-completer are not saved, the library has still ng2-completer.

**Comment by uap-universe** [comment]
Yes. The changes will be available in the npm registry, once version 3.0.0 is published.

**Comment by uap-universe** [comment]
@pj-alvarado10 version 3.0.0 is out now. There were considerably more breaking changes than I thought and the best course of action was to remove support for Angular 15 and below entirely.

If you need help migrating your project from smart table 2.10.0 to 3.0.0 please open _one_ ticket with all your questions. The [documentation](https://dj-fiorex.github.io/angular2-smart-table/documentation) page is also up to date and may help with some of the changes mentioned in the [CHANGELOG](https://github.com/dj-fiorex/angular2-smart-table/releases/tag/v3.0.0).

**Comment by pj-alvarado10** [comment]
Perfect! Thank you! angular2-smart-table are great! Your support and help are very appreciatted! And yes! I will open one ticket! The migration was good, but I only have a problem with filters that I will ask in the other ticket. This ticket was perfectly done!
