### ISSUE TITLE
Styles not being rendered like ng2-smart-table

### ISSUE THREAD

**Issue by ColinM9991** [dj-fiorex/angular2-smart-table#128]
Hi,

I've recently picked up a pet project and have discovered that ng2-smart-table is no longer supported.

In order to continue using supported packages, I have discovered this fork. What I have observed is that, when following the steps outlined in the README, the styles aren't rendering correctly if at all, whereas ng2-smart-table renders correctly.

Are there any additional steps required in setting up angular2-smart-table?

**Comment by uap-universe** [comment]
Hi! Welcome to our fork. Have you tried out the migration guide?
https://dj-fiorex.github.io/angular2-smart-table/migration
The styling drastically changed with the major upgrade to 2.x. Is there anything in particular, that you want back from the original style?

**Comment by ColinM9991** [comment]
> Hi! Welcome to our fork. Have you tried out the migration guide? https://dj-fiorex.github.io/angular2-smart-table/migration The styling drastically changed with the major upgrade to 2.x. Is there anything in particular, that you want back from the original style?

Thank you for your reply, and apologies if I took some time to get back to you - I was out of the country for a bit of time.

So here's what I see when I use ng2-smart-table
![image](https://user-images.githubusercontent.com/57466042/234674919-229e137f-b169-4902-b9b5-44809cfd463a.png)

On the other hand, with ng2-smart-table, using the minimal example from the readme, this is what I first see
![image](https://user-images.githubusercontent.com/57466042/234675021-b891013c-a75f-4256-84ce-527637d857cb.png)

When I click the X next to `ID` then it changes to this
![image](https://user-images.githubusercontent.com/57466042/234675104-37aa376f-177c-4742-bfad-ce68aefbe4f7.png)

Although the original styling isn't in place anymore, it does feel like no styling is in place. Is this the expected behavior?

I wasn't previously aware of the guide that you've linked to, though I would recommend maybe adding a link to this in the readme. What I can see now, however, is that the Quick Start in the GitHub.IO also contains some incorrect import statements such as this - or at least I'm unable to find `NgxSmartTableModule`
```typescript
import { NgxSmartTableModule } from 'angular2-smart-table';
```

**Comment by uap-universe** [comment]
Since there hasn't been activity for over one month now, I consider this as resolved.
