### ISSUE TITLE
defaultValue columns property not supported

### ISSUE THREAD

**Issue by nssoft-rlagrange** [dj-fiorex/angular2-smart-table#137]
Hi,

In the initial ng2-smart-table, we had a defaultValue property on column settings, in order to bring a value when the add button is clicked.
It's missing in your implementation.
Is it possible to bring it back ? An alternative would be a handler to provide a new object when the add button is clicked ?

Regards,

**Comment by uap-universe** [comment]
Unfortunately there is no `defaultValue` property in the [official documentation](https://akveo.github.io/ng2-smart-table/#/documentation) of the original ng2-smart-table. But I have looked into the code and I think I understand what this hidden feature did. It shouldn't be too complicated to add it in the next version.

**Comment by uap-universe** [comment]
Hello @nssoft-rlagrange 

please have a look at these two comments:

https://github.com/dj-fiorex/angular2-smart-table/blob/d1cce090871c64b6a4e6a52bd1ae4eb4b2417308/projects/angular2-smart-table/src/lib/lib/data-set/data-set.ts#L19-L20

https://github.com/dj-fiorex/angular2-smart-table/blob/d1cce090871c64b6a4e6a52bd1ae4eb4b2417308/projects/angular2-smart-table/src/lib/lib/data-set/data-set.ts#L173-L179

Having a `defaultValue` setting in `IColumn` would still leave the other attributes of the object undefined.

So I would like to implement the idea from the comment, to have a `valueCreateFunction` globally in the table settings, that is supposed to create an entirely valid object. 

Would that also solve your problem?

**Comment by nssoft-rlagrange** [comment]
That look like how I solved this in my code : 

settings.ts:24 : interface Settings {... , **newData?:any** } // provide a default data for any row creation
grid.ts:80 : this.dataSet = new DataSet([], this.settings.columns, **this.settings.newData ?? {}**); // settings sent to dataset
data-set.ts:8: newData:any; // new private property after newRow
data-set.ts:16:  constructor(data: Array<any> = [], protected columnSettings: IColumns, newData?:any)  // add newData to ctor
data-set.ts:20 : this.newData = newData; // in ctor, set new property
data-set.ts:178: this.newRow = new Row(-1, **Object.assign({}, this.newData)**, this); //duplicate the new data and set it to new row
row.ts:40 : (replace first line with theses two) : 
var copiedNewData = Object.assign({},this._dataSet.newData); // clone "newData" object to cut any object references to original data
const values = Object.assign(copiedNewData, this.data); //set to new row

Sorry again for not being able to provide a formal github pull request.

**Comment by uap-universe** [comment]
It's alright. I will implement it for version 3.1.0.
