### ISSUE TITLE
When no sort is given, the grid systematically sort the data by the first column

### ISSUE THREAD

**Issue by nssoft-rlagrange** [dj-fiorex/angular2-smart-table#139]
When no sort is configured, the data are sorted by the first column.

This is due to the Column ctor, taking a default value when settings is null (column.ts row 69) : 
this.defaultSortDirection = this.settings.sortDirection ?? 'asc';

I commented out the ternary to solve this issue.

**Comment by uap-universe** [comment]
Thank you for the report. To be honest, I cannot remember why it is that way. And the `reset()` method in the documentation talks about an "empty" sort. So I am not sure if there _was_ a reason to have this default, but it looks like it isn't documented anywhere.

Thus, I consider this a bug and fix it in the next version.
