### ISSUE TITLE
Add option to hide columns without showing tags

### ISSUE THREAD

**Issue by Et3rnal** [dj-fiorex/angular2-smart-table#147]
Thanks for maintaining the library, it is much appreciated.

I had a hard time migrating as I had a complex table.

Anyway I noticed we have these "tags" for hidden columns, I didn't have that prior to the update and I don't see how to disable that option?
![image](https://github.com/dj-fiorex/angular2-smart-table/assets/441522/fa0c3dc4-07ce-41f8-a550-5760119d736d)

I used CSS to do that but I was wondering if its optional.

**Comment by uap-universe** [comment]
I am afraid that this feature has been entirely changed without considering this use case.

We should consider adding this as an option in a future version.
