### ISSUE TITLE
Programmatically enable editing of rows

### ISSUE THREAD

**Issue by AnejVovcak** [dj-fiorex/angular2-smart-table#149]
I have a use case where a user could press a button, and they should be able to edit all rows of a smart table simultaneously. Is there a way of achieving this? I haven't found it so far.

**Comment by maixuanhan** [comment]
Should you query the edit buttons and click them?

**Comment by uap-universe** [comment]
No, you shouldn't. It's expensive. And most likely you don't want the events to be fired that are involved when clicking the button.

I _guess_ what the OP wants is to query the rows and then set the `isInEditing` flag of the row objects to `true`. 

You might want to limit that operation to visible rows, only.
