### ISSUE TITLE
Table filter not supporting addOperator argument after upgrading to v3.0.0

### ISSUE THREAD

**Issue by Tharrington86** [dj-fiorex/angular2-smart-table#153]
Hello,

I have a data table that has a filter for several different fields. After upgrading to v3.0.0 the filter is no longer working. As soon as a letter is typed, Q for example (which exists 0 times in my table) will find ALL records in the table. 

my filter method is as follows:
```typescript
/**
   * Sets filter on table depending on value of text string.
   * @param {string} text text for which to filter
   */
setFilterOnTable(text: string): void {
    if (text != null && text.length > 0) {
      this.summaries.setFilter(
        [
          { field: "id", search: text },
          { field: "company", search: text },
          { field: "partNum", search: text },
          { field: "createdAt", search: text },
        ],
        false
      );
    } else {
      this.summaries.setFilter([]);
    }
// Update the count of matches for the UI.
    this.searchCount = this.summaries.count();
```

Any idea how to restore the search functions functionality?

Angular 16
Nebular 12

**Comment by uap-universe** [comment]
I will try to reproduce this next week. In the meantime, can you please check the following?

* You set `doEmit = false` in your call to `setFilter`, which means you don't want to refresh the table there. Where is it refreshed, instead?
* Can you please check if `this.summaries.getFilteredAndSorted()` returns the correctly filtered data?
* Can you please share the column settings for those four columns?

**Comment by uap-universe** [comment]
I have taken a closer look at your example and realized, that it was probably never your intention to set `doEmit = false`.

The `false` argument in your call apparently refers to the removed `andOperator` argument and now accidentally maps to `doEmit`.

Please check #90 for the details.

**Comment by Tharrington86** [comment]
@uap-universe 

Ah, that does, in fact, appear to be what the problem is. I somehow overlooked that. Any ideas on how to restore the search function so it functions in a similar manner as before?

**Comment by uap-universe** [comment]
Yes. The essential part from the last comment in #90 is this:
> You can implement your own data source class by extending LocalDataSource and implement custom external filtering there s.t. the getFilteredAndSorted() method returns the data you want to display.

But this might already be a needlessly complicated solution, depending on your use case. I would start considering to `load()` only the data in the data source that should be displayed by the table and if that's too simple to cover your use case, start by extending the `LocalDataSource` class and only if that also isn't sufficient, implementing a merging logic in the column filter functions, that merge the table filter with the global external filter.
