### ISSUE TITLE
Expose the sorting and changing page function EventEmitter.

### ISSUE THREAD

**Issue by dtvu94** [dj-fiorex/angular2-smart-table#154]
Hello,

I am utilizing angular2-smart-table for Angular 16 version 3.1.1.
I am curious as to whether the interface could expose the EventEmitter of the sorting and page-changing functions so that they could be listened to.

**Comment by uap-universe** [comment]
I'm not sure if I get your question right.

But isn't subscribing to this observer exactly what you want to do?
https://github.com/dj-fiorex/angular2-smart-table/blob/2168ec984e3412febbd0928c472458e387ea10d9/projects/angular2-smart-table/src/lib/lib/data-source/data-source.ts#L77

**Comment by dtvu94** [comment]
Yes, thank you so much.
Yesterday, I found the local data source and write one to customize the sort and pagination.
