### ISSUE TITLE
Missing option to pass full row object to custom cell component

### ISSUE THREAD

**Issue by predefinedx** [dj-fiorex/angular2-smart-table#156]
Previously (in ng2-smart-table) it was possible to receive full row data object just by adding `value` variable in custom component. Now, it is not rendering correctly + it seems like it is impossible to get full row data in the custom component, only the value of one column.

**Comment by uap-universe** [comment]
Yes, the behavior changed with release 3.0. Probably something we might want to add retrospectively to the [migration page](https://dj-fiorex.github.io/angular2-smart-table/migration).
