### ISSUE TITLE
Table forces default sorting by first column of the table

### ISSUE THREAD

**Issue by predefinedx** [dj-fiorex/angular2-smart-table#157]
When table is being initialized, sorting is automatically added to the first column of the table. Why? Even after disabling sort for first column, it still is being sorted by first column values.

**Comment by predefinedx** [comment]
I will try to find time to look back at that project. 

I see, that the column sort is applied by seeing sorting arrow + on component initializing, first call for data from API is sending data sorting properties - sorting ASC by first column. 
My data source is API, which sorts data accordingly to received info from frontend, and in this case, filters are being set by smart-table package.

**Comment by uap-universe** [comment]
@predefinedx do you still have the problem? For the Angular 18 support I will be releasing the 3.3.0, soon. So if there's something that might need to be slapped into that release, let me know.

**Comment by predefinedx** [comment]
Looks like i have solved this one on my side, but just to be sure, I’ll check again in couple hours. I’ll post a coment with the problem i had (if I solved it) or with confirmation that problem still exists, and will include column settings

**Comment by uap-universe** [comment]
Closing stale issue.
