### ISSUE TITLE
Pagination /  Icons / table-borders Styling is messed up

### ISSUE THREAD

**Issue by ahmed-hachani** [dj-fiorex/angular2-smart-table#161]
Hello, I had to perform migration from angular 12 to 15 on a project and thankfully I found this fork, however this is how the table looks right now: 
![Capture d’écran 2024-07-01 151142](https://github.com/dj-fiorex/angular2-smart-table/assets/93057879/bd7fb180-599d-4ffd-a6a4-ff6840d159c6)
Am I missing some configuration?

**Comment by uap-universe** [comment]
Please take a look at the [migration guide](https://dj-fiorex.github.io/angular2-smart-table/migration), first. If it does not answer all your questions, please try to ask as specific as possible. This way I can probably add your questions directly to the migration guide.
