### ISSUE TITLE
Support for Angular 18?

### ISSUE THREAD

**Issue by verbosetechlabs** [dj-fiorex/angular2-smart-table#163]
Thanks to the fantastic work of the developers, I was able to successfully upgrade my project from Angular 15 to Angular 17. Are there any plans to support Angular 18 in the future? If so, could someone point me in the right direction so I can potentially submit a pull request for the update?

**Comment by uap-universe** [comment]
Oh is it that time already... :sweat_smile:  

Thanks for the reminder. Expect it within a week.

**Comment by uap-universe** [comment]
@verbosetechlabs version 3.3.0 now has Angular 18 support.
