### ISSUE TITLE
Support for cell heading (th element) within row scope on tbody

### ISSUE THREAD

**Issue by jlipscomb** [dj-fiorex/angular2-smart-table#165]
For section 508 needs, there are times which a cell within a row requires to be a th rather than a td.

Let's use the demo table for the working example. Assume that there are three rows which have been enabled for edit.

When navigating the table with an accessibility tool, such as the screen reader JAWS, it would be beneficial for the full name column to become a th for the row scope such that the screen reader would announce the name when using the JAWS built in table navigation mechanism. Each column navigated to within the row would state the value expressed in the th cell.

The tbody.component.html is hard coded to only support td based cells with no support of th based cells. Enhancing the application to support th row based scope cells would assist with meeting accessibility needs.

I have not seen such a mechanic to allow the th row based scope. There is support for native th column scope; just no support for th row based scope.

**Comment by uap-universe** [comment]
I am not sure that I get 100% of the requirements.

Is it actually sufficient to add an `isHeading` Boolean to the column settings and render `th` instead of `td` in each row when it is set to `true`?

Or is it more complicated than that and needs to be determined row by row?

**Comment by jlipscomb** [comment]
I am not sure the details of the logic as I have not looked into the entirety of this project. I am not sure I would have meaningful input to state where the setting should be. I would recommend, however, that if it is placed on the column as a setting that the setting be named `isRowHeading` and the default state to be false.

I believe that you have the general concept. 😄 

Tables can have a mixture of th and td elements within the rows within the tbody; meaning 0 - n th elements and (typically) 1 - n td elements. The thead would remain unchanged as it should only contain th. Below are some examples, just to make sure we are on the same page.

Here is a mix table structure where the thead and tbody utilize th elements.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th

Here is a table structure where the implicit tbody make use of th elements for yielding a vertical table.
https://www.w3schools.com/html/tryit.asp?filename=tryhtml_table_th_vertical

**Comment by uap-universe** [comment]
I'd prefer to name the setting `isRowHeading`.

I will also add the correct scope attribute to the `th` elements, just as a precaution to make it clearly defined across all browsers.
