### ISSUE TITLE
Row backgrounds and pagination differ from ng2-smart-table

### ISSUE THREAD

**Issue by matzrm** [dj-fiorex/angular2-smart-table#27]
Hi,

just switched from ng2-smart-table to your fork. This is the result:
![image](https://user-images.githubusercontent.com/8723543/144634010-a37f9f5b-ce76-44dc-a204-3e954d443657.png)

The rows background color is the same for all and the pager is not aligned to center.

Just write to know if I have a enviroment issues or is ok.

Regards

**Comment by hexdecimal16** [comment]
@matzrm can you show your setup for the table

**Comment by uap-universe** [comment]
Closed due to inactivity. Maybe solved with #66
