### ISSUE TITLE
LocalDataSource empty() and load([]) are not equivalent

### ISSUE THREAD

**Issue by uap-universe** [dj-fiorex/angular2-smart-table#31]
Consider the following two calls on a LocalDataSource:

```Typescript
this.source.load([]).then();  // smart table automatically refreshes
this.source.empty().then(); // smart table does not refresh
```

Workaround:
```Typescript
this.source.empty().then(() => this.source.refresh());
```
Conjecture:

The base class `DataSource` emits `onChanged` events in both cases, but with different actions. My guess is that the smart table reacts on an `onChanged` event with action `load` (and `refresh` of course) but does not react on an `onChanged` event with action `empty`.

**Comment by hexdecimal16** [comment]
@uap-universe I have created a sample app and the behviour is as expected. On calling `this.source.empty().then();` data is refreshed in the table as well. You can close this issue.

**Comment by hexdecimal16** [comment]
with this i believe milestone 2.1.0 is achieved I request you to please release the package.

**Comment by uap-universe** [comment]
Can you please _provide_ the example program s.t. I can verify? The current state of my investigation is that the `empty` event is not listed in this code:

https://github.com/dj-fiorex/angular2-smart-table/blob/ab4f2c51e19b6591a8b7a53e66b3f32444819de7/projects/angular2-smart-table/src/lib/lib/grid.ts#L214

**Comment by hexdecimal16** [comment]
@uap-universe https://github.com/hexdecimal16/test-issues-31

**Comment by hexdecimal16** [comment]
@uap-universe I am closing this for now in favour to release ver 2.1.0, please feel free to reopen the issue if you are not satisfied

**Comment by uap-universe** [comment]
@hexdecimal16 I don't know what you mean. When I execute your test application, I get a table with the row "Leanne Graham" displayed. Which *should* not be visible anymore, because you call `empty()`. Only when I add `this.source.refresh();` it works properly.

Maybe it is a timing problem and your test case is "broken", because you call `load` before `empty` without waiting that all events have been processed. So `load` maybe enqueues an event that is dispatched after the call to `empty()`.

What happens on your machine, when you move the `empty()` call into the `then()` part of the above promise? Like so:

```typescript
     ngOnInit(): void {
       //  Testing bug https://github.com/dj-fiorex/angular2-smart-table/issues    /31
       this.source.load(this.data).then(_ => this.source.empty().then());
       // setTimeout(() => this.source.refresh(),0); // uncomment to verify
     }

```

**Comment by hexdecimal16** [comment]
> @hexdecimal16 I don't know what you mean. When I execute your test application, I get a table with the row "Leanne Graham" displayed. Which _should_ not be visible anymore, because you call `empty()`. Only when I add `this.source.refresh();` it works properly.
> 
> Maybe it is a timing problem and your test case is "broken", because you call `load` before `empty` without waiting that all events have been processed. So `load` maybe enqueues an event that is dispatched after the call to `empty()`.
> 
> What happens on your machine, when you move the `empty()` call into the `then()` part of the above promise? Like so:
> 
> ```ts
>      ngOnInit(): void {
>        //  Testing bug https://github.com/dj-fiorex/angular2-smart-table/issues    /31
>        this.source.load(this.data).then(_ => this.source.empty().then());
>        // setTimeout(() => this.source.refresh(),0); // uncomment to verify
>      }
> ```
`this.source.load(this.data).then(_ => this.source.empty().then());` this doesn't empties the table. But when you do this
```
  this.source.load(this.data);
  this.source.empty().then();
```
It empties the table. The catch is to use then with empty.

**Comment by uap-universe** [comment]
@hexdecimal16 No it is not. And as I said, your example program does not work on every platform. Maybe on your machine for some timing reason. 

The thing is: if there was no bug here, then `this.source.load(this.data).then(_ => this.source.empty().then());` *would* work.

You can also verify it like this:

```
 this.source.load(this.data).then();
setTimeout(() =>  this.source.empty().then(), 5000);
```

Please tell me, if after 5 seconds your table gets emptied.

**Comment by hexdecimal16** [comment]
You are right we need to add empty to the list. Are you commiting this?

**Comment by uap-universe** [comment]
@hexdecimal16 yes, I do. If you are sure that this is a correct fix, I agree. I was not 100% certain, though, that it is that simple.

**Comment by hexdecimal16** [comment]
@uap-universe I tried locally it was working, you can also test.
