### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by uap-universe** [dj-fiorex/angular2-smart-table#33]
This is a manually maintained project without a dependency bot creating issues for us.

Therefore we must update the dependencies before releasing the next version.

**Comment by uap-universe** [comment]
The first update is already done by 4a79c726f9ebd1e353b273d41fc4127c012e0ac6. We should check again before releasing.

**Comment by hexdecimal16** [comment]
@dj-fiorex please review this and release the package as we don't want to create another fork for our project.

**Comment by dj-fiorex** [comment]
Done!

**Comment by dj-fiorex** [comment]
@hexdecimal16 @uap-universe please write your npm username so I cannot add you on npm registry also! So you can publish. I don't want to be the bottleneck of this project!

**Comment by hexdecimal16** [comment]
@dj-fiorex here is my username dhairy and email as well dhairytripathi@gmail.com

**Comment by uap-universe** [comment]
@dj-fiorex It is uap-universe an email is universe@uap-core.de
