### ISSUE TITLE
"Select All" does not fire userRowSelect anymore

### ISSUE THREAD

**Issue by uap-universe** [dj-fiorex/angular2-smart-table#37]
Maybe this is a bug, or maybe this is just a change that needs to be documented in the migration guide.

The observation is that in the original smart table implementation a click on the "select all" checkbox in the column header of the selection column fired the select events for the individual items.

The current implementation does not.

This might be a reasonable change, but it is also a breaking change. Need to investigate.

**Comment by hexdecimal16** [comment]
@uap-universe @dj-fiorex please review my PR
