### ISSUE TITLE
How to set the style of the table like ngx-admin-smart-table 

### ISSUE THREAD

**Issue by tim6400** [dj-fiorex/angular2-smart-table#66]
How to add the orignal style of the table like that in the [ngx-demo-Smart Table](https://www.akveo.com/ngx-admin/pages/tables/smart-table)?
I found this file: node_modules\@nebular\theme\styles\global\tables\_smart-table.theme.scss [nebular github](https://github.com/akveo/nebular/blob/master/src/framework/theme/styles/global/tables/_smart-table.theme.scss)
But of course as this package name **angular2-smart-table** and not **ng-smart-table** as the original package the style not apply.

Any idea how to set the origianl style?

**Comment by uap-universe** [comment]
You can try replacing all occurrences of `ng2-` with `angular2-`.

But I cannot guarantee that this will yield exactly the same appearance as in the original version. But it might come a little closer.

**Comment by tim6400** [comment]
Thank you
