### ISSUE TITLE
Functions to hide or disable actions

### ISSUE THREAD

**Issue by uap-universe** [dj-fiorex/angular2-smart-table#83]
For every row action (default *and* custom) we should add functions that map row data to a boolean determining whether the action is disabled or completely hidden. For the header actions (currently this is only the add action), the function does not take an input parameter.

Example settings:

```typescript
actions: {
  add: true,
  edit: {
    hiddenWhen: (data) => !data.readonly
  },
  delete: {
    disabledWhen: (data) => data.used
  },
}
```

or

```typescript
someExternalFlag = false;

actions: {
  add: {
    disabledWhen() => this.someExternalFlag
  }
  edit: false,
  delete: true,
}
```

For compatibility it is mandatory that the settings field keep their `boolean` type. So the new type would be `boolean | ActionSettings`.

relates to #82 
relates to #81 
resolves #2

**Comment by beamop** [comment]
Cool feature, will it be possible to also define whether we want to show or hide the expand button?

**Comment by uap-universe** [comment]
It _should_ be possible.

**Comment by uap-universe** [comment]
I gave it a second thought and instead of messing up the `actions` property, I'd rather extend the action configurations (add, edit, delete, expand).

**Comment by uap-universe** [comment]
Forgot to tag the issue in the commit :-/

48a2d48782a02ee4027c7e3cae96644f3d8739ac
