### ISSUE TITLE
Declare compatibility to Angular 14 in the package.json

### ISSUE THREAD

**Issue by stephanrauh** [dj-fiorex/angular2-smart-table#84]
Please add Angular 14 to your peer dependencies. Currently, I can only compile by using `npm install --force` or by declaring `overrides` in my package.json. The updated version of your `package.json` will look something like this:

```json
  "peerDependencies": {
    "@angular/common": "^13.0.0 || ^ 14.0.0",
    "@angular/core": "^13.0.0 || ^ 14.0.0",
    "@angular/forms": "^13.0.0 || ^ 14.0.0",
    "angular2-multiselect-dropdown": "^5.0.4",
    "lodash-es": "^4.17.21",
    "ng2-completer": "^9.0.1"
  },
```

Thanks in advance,
Stephan

**Comment by stephanrauh** [comment]
Yeah, sometimes npm is a mystery. :) Thanks for looking into it!

**Comment by furkick** [comment]
Hey, did this get fixed? as I am getting these dependency build errors.

**Comment by stephanrauh** [comment]
Yes, it works for me. Here's my project - maybe I've configured it differently: https://github.com/stephanrauh/extended-pdf-viewer-showcase/blob/dcd438e8a102e6bebb4a3b84af096943adf786a7/package.json#L36

**Comment by furkick** [comment]
I'm not sure, I had to manually add these three packages to get the build to succeed:

1. ng2-completer
2. angular2-multiselect-dropdown
3. lodash-es

Maybe an edge case but adding them fixed it for me.
