### ISSUE TITLE
Initial selection for editor list is wrong

### ISSUE THREAD

**Issue by juulian98** [dj-fiorex/angular2-smart-table#87]
When using the editor of the type "list", I noticed that the first selection is always automatically set as the default when clicking in Edit. This means that the filter element that is currently set in the line is not preselected.
As far as I could test, this behaviour did not occur with ng2-smart-table.

![image](https://user-images.githubusercontent.com/62206873/176118032-ea7396b1-0c8e-4412-9c8a-70936d6953fc.png)

![image](https://user-images.githubusercontent.com/62206873/176119167-c2802cf6-7453-4581-b0a3-20b18a0af0a8.png)

![image](https://user-images.githubusercontent.com/62206873/176119284-95c34d2b-4df8-4b3d-9ab9-efa57537f596.png)

**Comment by uap-universe** [comment]
I can confirm this via the [demo application](https://dj-fiorex.github.io/angular2-smart-table/examples/custom-editors-viewers).

However, in the [ng2-smart-table demo](https://akveo.github.io/ng2-smart-table/#/examples/custom-editors-viewers) it seems that there is nothing selected at all. So I suspect that is something that never worked properly.
