### ISSUE TITLE
Incomplete idea of filter config with different operators

### ISSUE THREAD

**Issue by uap-universe** [dj-fiorex/angular2-smart-table#90]
It seems there was a feature hacked into the filter configuration that allows to combine filters with OR instead of AND.

This feature is, however, very incomplete for the following reasons:

1. It is not implemented for ServerDataSource
2. The filter implementation is expensive (it applies each field individually as AND filter with one criterion and then merges the results and tries to get rid of duplicates afterwards instead of properly implementing the OR operator)
3. It is not possible to combine AND and OR (despite the `addFilter` signature might suggest that)
4. The default filter row always reverts the operator back to AND when used

Improving or removing this feature would be both breaking changes. So this issue here is just a reminder that something should be done about this in case a major upgrade is planned eventually.

**Comment by uap-universe** [comment]
The solution is to remove the concept of "operators" and only work with a conjunction of filters for the individual columns.

Secondly, we add a `removeFilter()` method. In the current implementation, it is only possible to remove a filter by using `setFilter()` method with an *empty* set of filters and then re-add all filters that are actually wanted.

The reason why this works is, that "empty string" is ignored by the filter method in the data source. So the lifecycle of a filter is like this:

1. It starts without a filter for a column
2. Once the filter in the table header is used, a filter config is added with the query the user entered
3. When the user removes the filter, the filter is **not** actually removed, but instead the query is changed to an empty string
4. Since empty strings are treated as "no filter is set", it looks like the filter was removed, but it actually isn't

**Comment by kw-pro** [comment]
Hello,
I use the ng2-smart-table before I switch to Angular 16.
Then I switch to angular2-smart-table. Now the OR-Filter Configuration ist not working anymore.
I try to use a ColumnFilterFunction, but I cannot use more than one Column.
Do you have an idea how I can solve this?
Thank you in Advance

**Comment by uap-universe** [comment]
Yes. You can implement your own data source class by extending `LocalDataSource` and implement custom external filtering there s.t. the `getFilteredAndSorted()` method returns the data you want to display.

I recommend to disable all built-in filtering stuff when you implement custom external filters (like e.g. a textfield which allows you to define a query). Otherwise your custom filter might need to merge the built-in filter config with your own filter config and apply that to the data before returning it from `getFilteredAndSorted()`.
